model:
  lens_parameterization:
    class_path: eisoptx.optimization.parameterization.LensParameterization
    init_args:
      lens_sequence: s-R-R-R-R-R-R-
      a: []
      c: [-0.1318524, -0.009671161, 0.01384346, -0.07709134, -0.02417337, 0.02399523, 0.0008580669,
          -0.05213183, 0.0199413, -0.02624121, 0.06731685, 0.02642347]
      d: []
      dpgf: [0.0023, 0.0092, 0.0109, 0.0051, 0.0045, 0.0051]
      m: []
      nd: [2.0033, 1.688931, 1.85478, 1.618, 1.603001, 1.618]
      s: [1.655731, 2.981271, 0.4993169, 4.003304, 11.29671, 2.191465, 1.427392, 4.002521,
          0.4977314, 4.002225, 0.4968129, 4.002317, 20.0]
      vd: [28.27312, 31.07492, 24.79852, 63.33265, 65.4369, 63.33265]
      nominal_wavelength: 550.
      freeze:
        s:  # Freeze last thickness; working distance is fixed
          default: False
          toggle_row_col_list: [-1]
        c:  # Freeze last curvature; the last one is solved for
          default: False
          toggle_row_col_list: [-1]
        g: False
        a: False
        d: False
        m: False
      target_efl: 10.
      solve_type: focal_length
      solve_idx: -1
      paraxial_image_solve: False
      total_track_length_solve:
      qc_vars: False
      scale_factor: 4.
      bezier_aspherics: True
      glass_file: configs/recommended_ohara_glass.csv
      misc_surface_model:
