model:
  lens_parameterization:
    class_path: eisoptx.optimization.parameterization.LensParameterization
    init_args:
      lens_sequence: s-R-R-R-R-R-R-
      a: []
      c: [-0.00573243, 0.09488434, 0.07691177, -0.02985548, -0.06231584, 0.05689214, 0.04526554,
          -0.09348504, 0.05409341, -0.0120519, 0.1334023, 0.061447]
      d: []
      dpgf: [0.0054, 0.0162, 0.0109, 0.0045, 0.0045, 0.0045]
      m: []
      nd: [1.7888, 1.784723, 1.85478, 1.603001, 1.603001, 1.603001]
      s: [0.5464452, 0.9984173, 0.9705895, 4.001979, 14.22929, 0.999436, 0.5759789, 3.558903,
          4.134864, 4.000426, 0.4992805, 2.280273, 8.0]
      vd: [28.4283, 25.68315, 24.79852, 65.4369, 65.4369, 65.4369]
      nominal_wavelength: 550.
      freeze:
        s:  # Freeze last thickness; working distance is fixed
          default: False
          toggle_row_col_list: [-1]
        c:  # Freeze last curvature; the last one is solved for
          default: False
          toggle_row_col_list: [-1]
        g: False
        a: False
        d: False
        m: False
      target_efl: 10.
      solve_type: focal_length
      solve_idx: -1
      paraxial_image_solve: False
      total_track_length_solve:
      qc_vars: False
      scale_factor: 4.
      bezier_aspherics: True
      glass_file: configs/recommended_ohara_glass.csv
      misc_surface_model:
