model:
  lens_parameterization:
    class_path: eisoptx.optimization.parameterization.LensParameterization
    init_args:
      lens_sequence: s-R-R-R-R-R-R-
      a: []
      c: [-0.09213594, 0.03588341, 0.03712164, -0.05429941, -0.02760947, 0.03410519, 0.019566,
          -0.04856076, 0.0283284, -0.02127334, 0.07999725, 0.03009538]
      d: []
      dpgf: [0.0054, 0.0162, 0.0109, 0.0045, 0.0045, 0.0045]
      m: []
      nd: [1.7888, 1.784723, 1.85478, 1.603001, 1.603001, 1.603001]
      s: [1.274054, 2.800269, 0.4998926, 4.002307, 20.06362, 2.077542, 0.9367607, 4.001577,
          0.4983007, 3.422158, 0.4977459, 4.001256, 16.0]
      vd: [28.4283, 25.68315, 24.79852, 65.4369, 65.4369, 65.4369]
      nominal_wavelength: 550.
      freeze:
        s:  # Freeze last thickness; working distance is fixed
          default: False
          toggle_row_col_list: [-1]
        c:  # Freeze last curvature; the last one is solved for
          default: False
          toggle_row_col_list: [-1]
        g: False
        a: False
        d: False
        m: False
      target_efl: 10.
      solve_type: focal_length
      solve_idx: -1
      paraxial_image_solve: False
      total_track_length_solve:
      qc_vars: False
      scale_factor: 4.
      bezier_aspherics: True
      glass_file: configs/recommended_ohara_glass.csv
      misc_surface_model:
