name: eisoptx
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch
  - pytorch-cuda=12.4
  - torchvision
  - torchmetrics
  - scipy
  - pandas
  - matplotlib
  - tensorboard
  - pip
  - pip:
    - lightning
    - jsonargparse[signatures]>4.20.0
