model:
  # Based on GS3-U3-41C6C-C 1" FLIR Grasshopper®3 High Performance USB 3.0 Color Camera
  # https://www.edmundoptics.com/p/gs3-u3-41c6c-c-1-grasshopper-usb-30-color-camera/30772/
  # Sensor: CMOSIS CMV4000
  ray_initialization:
    class_path: eisoptx.modeling.ray_initialization.RayInitialization
    init_args:
      aperture_type: f_number
      aperture: 2.
      hfov: 15.88  # Sensor diag = 15.93mm; EFL = 28mm;
      n_fields: 11
      pupil_sampling_mode: skew_uniform_jittered
      pupil_sampling_kwargs:
        n_r: 16
        n_i: 1
      ray_aiming_steps: 0
      ray_aiming_locations: tbs
      field_stop_position:
      wavelengths: [390., 420., 450., 480., 510., 540., 570., 600., 630., 660., 690.]
      wavelength_weights: [0.024,  0.0765, 0.0962, 0.1083, 0.1222, 0.1104, 0.0858, 0.1248, 0.1089, 0.1048, 0.0381]
  # Optics simulator
  optics_simulator:
    class_path: eisoptx.modeling.simulation.OpticsSimulator
    init_args:
#      sensor_diagonal:
      shape: [2048, 2048]
      shape_type: image
      psf_abs_size: 269.5e-03  # Pixel pitch: 5.5 um; PSF size: 49x49
      sigma_rel: 1.
      diffraction_f_number: 2.
      kernel_type: linear
      psf_grid_shape: [3, 3]
      wavelength_weights:
        - [0.0256, 0.0282, 0.0087, 0.0063, 0.0111, 0.0213, 0.0257, 0.2531, 0.2767, 0.2603, 0.0828]
        - [0.0104, 0.0256, 0.0369, 0.0727, 0.1959, 0.256,  0.208,  0.1043, 0.0372, 0.0334, 0.0196]
        - [0.036,  0.1758, 0.243,  0.246,  0.1595, 0.054,  0.0238, 0.0169, 0.0128, 0.0206, 0.0118]
      patch_overlap: 0.25
  e2e_vector_mode:
  e2e_loss_weight:  # If None, monitor only
  # Residuals
  residuals:
    - class_path: eisoptx.optimization.residuals.TransverseRayAberrationResiduals
      init_args:
        weight: 1.
    - class_path: eisoptx.optimization.residuals.RayPathResiduals
      init_args:
        weight: 20.
        min_cutoff: .25
        max_cutoff: .inf
        min_cutoff_refractive: 1.
        max_cutoff_refractive: 5.
        min_cutoff_refractive_relative: 0.3333
        max_cutoff_refractive_relative: 3.
        other_min_cutoffs: [[-1, 20.]]
        other_max_cutoffs: []
    - class_path: eisoptx.optimization.residuals.RayAngleResiduals
      init_args:
        weight: 10.
        max_angle: 60.
    - class_path: eisoptx.optimization.residuals.DistortionResiduals
      init_args:
        weight: 10.
        threshold: 0.02
    - class_path: eisoptx.optimization.residuals.GlassVariableResiduals
      init_args:
        weight:
    - class_path: eisoptx.optimization.residuals.GlassMeshDistanceResiduals
      init_args:
        weight: 1e-03
        threshold: 0.
        max_simplex_size: 1.25
  lens_optimizer:
    class_path: eisoptx.optimization.optimizers.LMOptimizer
    init_args:
      lm_parameter: 1e6
      damped_term_min: 1e-6
      tolerance: 1.25
      beta: .9
      lam_eps: 1e-8
      lam_increase_factor: 2.
      lam_decrease_factor: 3.
data:
  class_path: eisoptx.data.datasets.NoneDataModule
  init_args:
    n_samples: 100
trainer:

  accelerator: auto
  max_steps: 20000
  log_every_n_steps: 1
  val_check_interval: 100
  check_val_every_n_epoch:
  precision: 64
  logger:
    class_path: eisoptx.main.CustomLogger
    init_args:
      save_dir: logs/logs_fab
  callbacks:
    - eisoptx.utils.callbacks.ExtendedLoggingCallback
    - class_path: eisoptx.utils.callbacks.CodeVSeqFileCallback
      init_args:
        use_private_catalog: True
    - eisoptx.utils.callbacks.ConfigFileCallback
    - eisoptx.main.CustomProgressBar
    - class_path: ModelCheckpoint
      init_args:
        every_n_train_steps: 100
    - class_path: eisoptx.utils.callbacks.IncreaseGlassVariableResidualsWeightCallback
      init_args:
        initial_step: 0.
        final_step: .5
        n_increments: 25
        initial_weight: 0.00001525878  # 2**-16
        final_weight: 512  # 2**9
    - class_path: eisoptx.utils.callbacks.ToggleGlassOptimizationCallback
      init_args:
        initial_step: 0.
        final_step: .5
        n_cycles: 25
    - class_path: eisoptx.utils.callbacks.BindMaterialsCallback
      init_args:
        step: .5
    - class_path: eisoptx.utils.visualization.VisualizationCallback
      init_args:
        every_n_steps: 25
        visualizations:
          - class_path: eisoptx.utils.visualization.LensLayout
            init_args:
              wavelengths: [450., 650., 550.]
              n_fields: 2
              n_rays: 5
              rc_params:
                figure.figsize: '2.6, 1.6'
                lines.linewidth: '.75'
                axes.linewidth: '.75'
                xtick.major.size: '5.'
                xtick.minor.size: '3.'
                ytick.major.size: '5.'
                ytick.minor.size: '3.'
          - class_path: eisoptx.utils.visualization.RGBPSFs
            init_args:
              field_indices: [0, 2, 4, 6, 8, 10]
              sqrt_scale: False
              normalize_by_max: True
              cmap: inferno
              rc_params:
                figure.figsize: '3.2, 1.6'
                figure.constrained_layout.h_pad: 0.015625
                figure.constrained_layout.w_pad: 0.015625
                font.size: '6'
          - class_path: eisoptx.utils.visualization.PSFs
            init_args:
              wavelength_indices: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
              field_indices: [0, 2, 4, 6, 8, 10]
              sqrt_scale: False
              normalize_by_max: True
              cmap: inferno
              rc_params:
                figure.figsize: '3.2, 5.6'
                figure.constrained_layout.h_pad: 0.015625
                figure.constrained_layout.w_pad: 0.015625
                font.size: '6'
          - class_path: eisoptx.utils.visualization.GlassPlot
            init_args:
              plot_partial_dispersion: True
              rc_params:
                figure.figsize: '3.2, 4.0'
                lines.linewidth: '1.'
        save_formats: []
        rc_params:
          figure.constrained_layout.use: 'True'
          figure.dpi: '200'
          font.size: '7'